version: '3'

services:
  bouncer:
    image: php:8.2-apache
    ports:
      - 8888:80
    volumes:
      - .:/var/www
    command:
      [
        "bash",
        "-c",
        "a2enmod rewrite && apache2-foreground",
      ]
