version: '3'

services:
  bouncer:
    image: php:8.2-apache
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost/?purge=true | grep -q 
OK"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s
    ports:
      - 8888:80
    volumes:
      - .:/var/www
    command:
      [
        "bash",
        "-c",
        "a2enmod rewrite && chown -R www-data:www-data /var/www/public && chown -R www-data:www-data /var/www/storage && apache2-foreground",
      ]
