version: '3'

services:
  bouncer:
    image: php:8.2-apache
    ports:
      - 8888:80
    volumes:
      - .:/var/www
    command:
      [
        "bash",
        "-c",
        "a2enmod rewrite && chown -R www-data:www-data /var/www/public && chown -R www-data:www-data /var/www/storage && apache2-foreground",
      ]
